// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	parking "parkify-BE/features/parking"

	mock "github.com/stretchr/testify/mock"

	parkingslot "parkify-BE/features/parkingslot"

	user "parkify-BE/features/user"
)

// ParkingModel is an autogenerated mock type for the ParkingModel type
type ParkingModel struct {
	mock.Mock
}

// GetAllParking provides a mock function with given fields: userID
func (_m *ParkingModel) GetAllParking(userID uint) ([]parking.Parking, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllParking")
	}

	var r0 []parking.Parking
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]parking.Parking, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []parking.Parking); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]parking.Parking)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllSlotByID provides a mock function with given fields: parkingID
func (_m *ParkingModel) GetAllSlotByID(parkingID uint) ([]parkingslot.ParkingSlot, error) {
	ret := _m.Called(parkingID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSlotByID")
	}

	var r0 []parkingslot.ParkingSlot
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]parkingslot.ParkingSlot, error)); ok {
		return rf(parkingID)
	}
	if rf, ok := ret.Get(0).(func(uint) []parkingslot.ParkingSlot); ok {
		r0 = rf(parkingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]parkingslot.ParkingSlot)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(parkingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataByEmail provides a mock function with given fields: email
func (_m *ParkingModel) GetDataByEmail(email string) (user.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetDataByEmail")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (user.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) user.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataParkingByID provides a mock function with given fields: parkingID
func (_m *ParkingModel) GetDataParkingByID(parkingID uint) (parking.Parking, error) {
	ret := _m.Called(parkingID)

	if len(ret) == 0 {
		panic("no return value specified for GetDataParkingByID")
	}

	var r0 parking.Parking
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (parking.Parking, error)); ok {
		return rf(parkingID)
	}
	if rf, ok := ret.Get(0).(func(uint) parking.Parking); ok {
		r0 = rf(parkingID)
	} else {
		r0 = ret.Get(0).(parking.Parking)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(parkingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPicture provides a mock function with given fields: parkingID
func (_m *ParkingModel) GetPicture(parkingID int) (parking.Parking, error) {
	ret := _m.Called(parkingID)

	if len(ret) == 0 {
		panic("no return value specified for GetPicture")
	}

	var r0 parking.Parking
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (parking.Parking, error)); ok {
		return rf(parkingID)
	}
	if rf, ok := ret.Get(0).(func(int) parking.Parking); ok {
		r0 = rf(parkingID)
	} else {
		r0 = ret.Get(0).(parking.Parking)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(parkingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostParking provides a mock function with given fields: newData, email
func (_m *ParkingModel) PostParking(newData parking.Parking, email string) error {
	ret := _m.Called(newData, email)

	if len(ret) == 0 {
		panic("no return value specified for PostParking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(parking.Parking, string) error); ok {
		r0 = rf(newData, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: parkingID, updateFields, userID
func (_m *ParkingModel) Update(parkingID int, updateFields map[string]interface{}, userID uint) error {
	ret := _m.Called(parkingID, updateFields, userID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, map[string]interface{}, uint) error); ok {
		r0 = rf(parkingID, updateFields, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewParkingModel creates a new instance of ParkingModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParkingModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParkingModel {
	mock := &ParkingModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
